# Generated by Django 6.0.3 on 2026-04-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Volunteering',
            },
        ),
        migrations.CreateModel(
            name='VolunteeringDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('volunteering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolio.volunteering')),
            ],
        ),
    ]
